language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

install:
- "composer require codeclimate/php-test-reporter --dev"
- "composer update --no-interaction --prefer-stable"

script:
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
