#!/usr/bin/env php
<?php
error_reporting(E_ALL);

$autoloader = false;
foreach (array(__DIR__.'/../../autoload.php', __DIR__.'/../vendor/autoload.php', __DIR__.'/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require_once $file;
        $autoloader = true;
        break;
    }
}
if(!$autoloader) {
    error_log('[ERROR] Could not locate the autoloader. Check if you have it.');
    exit();
}

use PhpDocFormatter\Application;
use PhpDocFormatter\Config;
use Symfony\Component\Finder\Finder;
use PhpDocFormatter\CommandConfig;

$error = null;

try {
    $options = CommandConfig::getCliOptions($argv);
} catch (Exception $e) {
    $error = $e->getMessage();
}

$version = trim(file_get_contents(__DIR__.'/VERSION'));
if ($options[CommandConfig::VERSION]) {
    echo $version, PHP_EOL;
    exit;
}

error_log('');
error_log('phpDoc Formatter '.$version);
error_log('------------'.str_repeat('-', strlen($version)));

if ($error) {
    error_log('[ERROR] '.$error);
    $options[CommandConfig::HELP] = true; // Show help
}
if ($options[CommandConfig::HELP]) {
    $help = trim(file_get_contents(__DIR__.'/HELP'));
    error_log($help);
    exit;
}

$config = CommandConfig::getOptionsFile(getcwd());
CommandConfig::mergeOptions($config, $options);

try {
    $app = new Application($config);
} catch (Exception $e) {
    error_log('[ERROR] '.$error);
    exit();
}
$app->fixFiles();

